### ISSUE TITLE
401-feil

### ISSUE THREAD

**Issue by valosnah** [Informasjonsforvaltning/fdk-model-publisher#68]
"Traceback (most recent call last):
  File "/app/src/fdk_model_publisher/service/fetcher.py", line 46, in fetch
    response.raise_for_status()
  File "/usr/local/lib/python3.8/site-packages/aiohttp/client_reqrep.py", line 1004, in raise_for_status
    raise ClientResponseError(
aiohttp.client_exceptions.ClientResponseError: 401, message='', url=URL('https://oidc.difi.no/kontaktinfo-oauth2-server/rest/apis')
: Error connecting to https://oidc.difi.no/kontaktinfo-oauth2-server/rest/apis:401, message='', url=URL('https://oidc.difi.no/kontaktinfo-oauth2-server/rest/apis')"

**Comment by valosnah** [comment]
Arkivert tjeneste, lukker issue
